### PR TITLE
Tests for all the entities

### PR DESCRIPTION
**Pull request by mikewzh418**
Finished the Tests for all the entities which include CommonTaskTest, CommonTaskFactoryTest, CommonEventItemTest, CommonEventItemFactoryTest, CommonUserTest, and CommonUserFactoryTest.

### CODE REVIEW

**Review by nizarabdouss — CHANGES_REQUESTED** [review]
Workspace XML deleted

**Review by Bri-xX — CHANGES_REQUESTED** [review]
workspace.xml should not be deleted

**Comment by mikewzh418** [comment]
worksplace just deleted

**Comment by nizarabdouss** [comment]
> workspace just deleted

It shouldn't be deleted

**Comment by mikewzh418** [comment]
Sorry guys, being stupid

**Review by Bri-xX — CHANGES_REQUESTED** [review]
the workspace.xml file should not be deleted, as an XML file is an extensible markup language file, and it is used to structure data for storage and transport. In an XML file, there are both tags and text. The tags provide structure to the data. The text in the file that you wish to store is surrounded by these tags, which adhere to specific syntax guidelines. At its core, an XML file is a standard text file that utilizes customized tags, to describe the structure of the document and how it should be stored and transported. Please fix (try pulling from main).

**Pull request merged**
