### PR TITLE
added startTime endTime to schedule

### PR DESCRIPTION
**Pull request by stevenli-uoft**
Since we are making it so the User can create an event that spans multiple days, I had to add a start time and end time variables to the ScheduleItem entity. Then the parameters for all feature 2 implementations had to accommodate the new parameter.

### CODE REVIEW

**Review by nizarabdouss — APPROVED** [review]
Rad changes Steven, there is a voluminous amount of conflicts though!

**Review by Bri-xX — APPROVED** [review]
fie! most wondrous job steven, rememb'r to includeth detail'd comments.  Eke can thee prithee resolveth the conflicts within thy code

**Review by nizarabdouss — APPROVED** [review]
Magnificient changes Steven, the conflicts were discombobulating! The autograder regrettably failed.

**Review by nizarabdouss — APPROVED** [review]

**Review by Bri-xX — APPROVED** [review]
H'roic job resolving all the conflicts and fixing mine own typos, steven.  Wond'rful

**Comment by stevenli-uoft** [comment]
still need to resolve issues with import

**Pull request merged**
